In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
dataset = pd.read_csv('/content/winequality-red (2).csv')

In [7]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [8]:
dataset['quality'].unique()

array([5, 6, 7, 4, 8, 3])

In [9]:
X = dataset.iloc[: , 1:-1].values
y = dataset.iloc[:, -1].values

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X ,y, test_size=0.20)

In [12]:
from sklearn.preprocessing import StandardScaler

In [13]:
sc = StandardScaler()

In [14]:
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [15]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [17]:
l_cla = LogisticRegression()
k_cla = KNeighborsClassifier()
d_cla = DecisionTreeClassifier()
r_cla = RandomForestClassifier()
s_cla = SVC(kernel='linear')
ks_cla = SVC(kernel= 'rbf')

In [18]:
l_cla.fit(X_train, y_train)
k_cla.fit(X_train, y_train)
d_cla.fit(X_train, y_train)
r_cla.fit(X_train, y_train)
s_cla.fit(X_train, y_train)
ks_cla.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [19]:
l_pred = l_cla.predict(X_test)
k_pred = k_cla.predict(X_test)
d_pred = d_cla.predict(X_test)
r_pred = r_cla.predict(X_test)
s_pred = s_cla.predict(X_test)
ks_pred = ks_cla.predict(X_test)

In [20]:
from sklearn.metrics import confusion_matrix

In [21]:
l_c = confusion_matrix(y_test, l_pred)
k_c = confusion_matrix(y_test, k_pred)
d_c = confusion_matrix(y_test, d_pred)
r_c = confusion_matrix(y_test, r_pred)
s_c = confusion_matrix(y_test, s_pred)
ks_c = confusion_matrix(y_test, ks_pred)

In [22]:
l_c

array([[ 0,  0,  1,  1,  0,  0],
       [ 0,  0,  7,  4,  0,  0],
       [ 0,  0, 99, 42,  2,  0],
       [ 0,  0, 39, 78,  5,  0],
       [ 0,  0,  3, 22, 11,  0],
       [ 0,  0,  0,  2,  4,  0]])

In [23]:
k_c

array([[ 0,  0,  1,  1,  0,  0],
       [ 0,  0,  7,  4,  0,  0],
       [ 0,  2, 95, 44,  2,  0],
       [ 0,  1, 37, 72, 12,  0],
       [ 0,  0,  7, 19, 10,  0],
       [ 0,  0,  0,  1,  5,  0]])

In [24]:
d_c

array([[  0,   0,   2,   0,   0,   0],
       [  0,   0,   6,   5,   0,   0],
       [  0,   1, 111,  26,   5,   0],
       [  0,   2,  29,  76,  15,   0],
       [  0,   0,   3,  11,  22,   0],
       [  0,   0,   1,   2,   3,   0]])

In [25]:
r_c

array([[  0,   1,   1,   0,   0,   0],
       [  0,   0,   8,   3,   0,   0],
       [  0,   0, 112,  30,   1,   0],
       [  0,   2,  25,  88,   7,   0],
       [  0,   0,   2,  17,  17,   0],
       [  0,   0,   0,   4,   2,   0]])

In [26]:
s_c

array([[  0,   0,   1,   1,   0,   0],
       [  0,   0,   8,   3,   0,   0],
       [  0,   0, 102,  41,   0,   0],
       [  0,   0,  42,  80,   0,   0],
       [  0,   0,   3,  33,   0,   0],
       [  0,   0,   0,   6,   0,   0]])

In [27]:
ks_c

array([[  0,   0,   1,   1,   0,   0],
       [  0,   0,   8,   3,   0,   0],
       [  0,   0, 104,  38,   1,   0],
       [  0,   0,  36,  84,   2,   0],
       [  0,   0,   3,  26,   7,   0],
       [  0,   0,   0,   3,   3,   0]])

In [28]:
from sklearn.metrics import accuracy_score

In [29]:
l_a = accuracy_score(y_test, l_pred)
k_a = accuracy_score(y_test, k_pred)
d_a = accuracy_score(y_test, d_pred)
r_a = accuracy_score(y_test, r_pred)
s_a = accuracy_score(y_test, s_pred)
ks_a = accuracy_score(y_test, ks_pred)

In [30]:
print('Logistic Regression: ' + str(l_a) + '\nKNN: ' + str(k_a) + '\nDecision Tree: ' + str(d_a) + '\nRandom Forest: ' + str(r_a) + '\nLinear SVC: ' + str(s_a) + '\nKernel SVC: ' + str(l_a))

Logistic Regression: 0.5875
KNN: 0.553125
Decision Tree: 0.653125
Random Forest: 0.678125
Linear SVC: 0.56875
Kernel SVC: 0.5875
